### ISSUE TITLE
Application is not supported for this API version

### ISSUE THREAD

**Issue by pparmentier** [microsoftgraph/xamarin-csharp-snippets-sample#5]
Hi, I'm a noob in Azure =)
I'm trying to make this Graph API sample work .

I registered my app in Azure, got the Application-id and set it into the App.cs file from the sample. Everytime I try simple operations, I get this message :

Users.Get Me failed. Exception: AADSTS70001: Application 'My-APP-ID' is not supported for this API version.
I tried modifying the AuthenticationHelper.cs file to go from new

GraphServiceClient("https://graph.microsoft.com/v1.0",
to :

new GraphServiceClient("https://graph.microsoft.com/v1.6",
To try and get the 1.6 API version, hoping the issue would come from there. But I still get the same message over and over.

I chose this sample because all I have to do is set the App ID (I thought so) but I can't get it to work.

Do you have any idea on how I could get it to work ?

Thank you.

**Comment by jamescro** [comment]
It looks like you registered your application in the Azure Management Portal. This sample uses the [Azure AD v2 authentication endpoint](https://developer.microsoft.com/en-us/graph/docs/authorization/converged_auth). As noted in the Readme,  you'll need to register your app in the [App registration portal](https://apps.dev.microsoft.com/). You won't need to assign any permissions there, since this sample app requests the permission scopes dynamically.

**Comment by jamescro** [comment]
Closing for now. Please reopen if you have issues with a client id that you get from the App registration portal.
